CREATE TABLE `passport_details` (
  `PASSPORT_ID` int(11) NOT NULL,
  `PASSPORT_NUMBER` int(11) DEFAULT NULL,
  `PASSPORT_ISSUE_DATE` datetime DEFAULT NULL,
  `PASSPORT_EXPIRY_DATE` datetime DEFAULT NULL,
  `PERSON_ID` int(11) NOT NULL,
  PRIMARY KEY (`PASSPORT_ID`),
  KEY `FK_PERSON_ID` (`PERSON_ID`),
  CONSTRAINT `FK_PERSON_ID` FOREIGN KEY (`PERSON_ID`) REFERENCES `person` (`PERSON_ID`)
)

 CREATE TABLE `person` (
  `PERSON_ID` int(11) NOT NULL,
  `PERSON_NAME` varchar(255) DEFAULT NULL,
  `PERSON_DOB` date DEFAULT NULL,
  PRIMARY KEY (`PERSON_ID`)
)